### ISSUE TITLE
Providing an empty map for Context.env results in environment dump on SSH.run

### ISSUE THREAD

**Issue by brienw** [bitcrowd/sshkit.ex#101]
Just noticed this when adding `:env` option support to Bootleg. In the case that Context.env is set to an empty map `%{}` the resulting command from 'Context.build' contains a call to `export` with no parameters:
`SSH.run(context, "ls")` where context.env is `%{}`
produces:
`(export  && /usr/bin/env ls)`

The result is that `export` dumps the whole environment, which is then returned as `:stdout`

Desired behavior is that `Context.env` with a value of `%{}` would act the same as if it had a value of `nil`

**Comment by pmeinhardt** [comment]
Fixed, thanks to @brienw 🎉 – https://github.com/bitcrowd/sshkit.ex/pull/102
