### ISSUE TITLE
Make SSHKit downloads & uploads fully context-aware

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/sshkit.ex#121]
### Expected Behavior

The `SSHKit.dowload/3` and `upload/3` functions should respect the context options `path`, `user`, `group`, `env` & `umask` like `SSHKit.run/2` does.

### Actual Behavior

The `SSHKit.download/3` and `upload/3` functions are not yet fully context-aware. They only take the context `path` into account.

**Comment by klappradla** [comment]
With #140 in place, I think we can happily close this one 🎉
