### ISSUE TITLE
Handle glob expressions in SCP Download & Upload source parameter

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/sshkit.ex#144]
### Expected Behavior

Uploads should expand `source` values using [`Path.wildcard/2`](https://hexdocs.pm/elixir/Path.html#wildcard/2).

Downloads should check that paths of files and directories sent by the remote conform to the specified `source` pattern.

### Actual Behavior

Currently, SSHKit's SCP module does not properly handle glob expressions, e.g. `"path/**/*.log".

**Comment by pmeinhardt** [comment]
I think we'll drop the idea of supporting globs for file transfers for now. For SCP it may have been slightly easier to implement, but at the moment it doesn't seem like such a useful feature anymore.

> Glob expansion is not directly supported by the `:ssh_sftp` module,
implementation would differ a lot between uploads (expand locally) and
downloads (expand on remote) and, lastly, it's not quite clear what the
semantics should be in case of conflicting files names. I.e. would
globbed files be uploaded into the target directory, "flat"?
> 
> If needed by code using SSHKit, globbing support with specific semantics
can be implemented as a series of SSHKit uploads, one for each matched
source path.

— https://github.com/bitcrowd/sshkit.ex/pull/164/commits/78c91ca0f67c574b0fa9751474f45357ee3f78a7

**Comment by klappradla** [comment]
> […] globbing support with specific semantics
can be implemented as a series of SSHKit uploads, one for each matched
source path.

Perfectly fine and probably also easier to use 👍
