### ISSUE TITLE
SSH authentication using Kerberos ticket possible?

### ISSUE THREAD

**Issue by martijnversluis** [bitcrowd/sshkit.ex#146]
Is it possible to use Kerberos (keytab) authentication for SSH? SSHKit does not seem to support it, I’m getting: “Service not available” when deploying using Bootleg.

### Environment

* SSHKit.ex version (`mix deps`): 0.1.0
* Elixir & Erlang/OTP version (`elixir -v`): Elixir 1.8.1 (compiled with Erlang/OTP 21)
* Operating system (local): Debian 9.7
* Operating system (remote): Debian 8.3
* SSH version (remote, `ssh -V`): OpenSSH_6.7p1 Debian-5+deb8u1, OpenSSL 1.0.1k 8 Jan 2015

### Expected Behavior

Successful connection when `$KRB5CCNAME` points to a valid ticket (manual ssh connection using this ticket succeeds).

### Actual Behavior

```
13:15:01.545 [info]  Erlang SSH :client 4.7.3 (OpenSSL 1.1.0j  20 Nov 2018).
Server: 'SSH-2.0-OpenSSH_6.7p1 Debian-5'
Disconnects with code = 7 [RFC4253 11.1]: Service not available
State = {userauth_keyboard_interactive,client}
Module = ssh_no_io, Line = 48.
Details:
  User interaction is not allowed


** (SSHError) SSHKit returned an internal error on 10.190.7.118: 'Service not available'
    lib/bootleg/ssh.ex:76: anonymous fn/2 in Bootleg.SSH.run/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    lib/bootleg/ssh.ex:190: Bootleg.SSH.run!/2
    lib/bootleg/ssh.ex:95: Bootleg.SSH.validate_workspace/3
    lib/bootleg/ssh.ex:55: Bootleg.SSH.init/2
    deps/bootleg/lib/bootleg/tasks/deploy.exs:35: anonymous fn/3 in Bootleg.DynamicTasks.UploadRelease.execute/0
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
```

**Comment by martijnversluis** [comment]
Anybody here who can help me?

**Comment by klappradla** [comment]
Hey @martijnversluis 👋 

first of all: sorry for my suuuuper late response 🙈 _(things are quite busy at the moment)_

I'm only roughly familiar with the _"Kerberos"_ protocol and have never used it myself. I therefore can't even tell you if `SSHKit` "supports" it 🤷‍♂.

Generally speaking, `SSHKit` is only a convenience wrapper on top of Erlang's `ssh` application. So if you can archive what you want with "pure" Erlang or Elixir, you're a step closer to knowing about potential shortcomings of `Bootleg` or `SSHKit` here.

Have you tried this already?

**Comment by martijnversluis** [comment]
Hey @klappradla,

Thanks anyway for your reply. I searched the Erlang docs and googled around, but Erlang does not seem to support any bit of the protocol. I'm currently trying to build an alternative SSH driver for bootleg that uses shell commands. My expectation is that Kerberos auth will work then.

**Comment by chavenor** [comment]
@martijnversluis did you get this figured out having same issue.
