### ISSUE TITLE
deprecation warning in elixir 1.8

### ISSUE THREAD

**Issue by bitboxer** [bitcrowd/sshkit.ex#147]
### Environment

* SSHKit.ex version (`mix deps`):   sshkit 0.1.0
* Elixir & Erlang/OTP version (`elixir -v`): Elixir 1.8.2 (compiled with Erlang/OTP 20)
* Operating system (local): ubuntu
* Operating system (remote):  debian
* SSH version (remote, `ssh -V`):  OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017

### Expected Behavior

No deprecation warning

### Actual Behavior

I see this when deploying things using bootleg

```
warning: the Collectable protocol is deprecated for non-empty lists. The behaviour of things like Enum.into/2 or "for" comprehensions with an :into option is incorrect when collecting into non-empty lists. If you're collecting into a non-empty keyword list, consider using Keyword.merge/2 instead. If you're collecting into a non-empty list, consider concatenating the two lists with the ++ operator.
  (elixir) lib/collectable.ex:83: Collectable.List.into/1
  (elixir) lib/enum.ex:1227: Enum.into_protocol/2
  lib/sshkit/scp/command.ex:24: SSHKit.SCP.Command.flag/2
  lib/sshkit/scp/command.ex:17: SSHKit.SCP.Command.scp/3
  lib/sshkit/scp/upload.ex:84: SSHKit.SCP.Upload.start/2
```

**Comment by bitboxer** [comment]
Yes, will add a ticket to bootleg and write the code for the PR there once #148 is merged. Thanks!

**Comment by pmeinhardt** [comment]
Awesome! Thank you 🙂 💚

**Comment by pmeinhardt** [comment]
FYI: We just released 0.2.0 with the fix ✌️

**Comment by bitboxer** [comment]
Thanks! Will create the PR tomorrow morning <3

**Comment by bitboxer** [comment]
I now created the PR to sshkit
