### ISSUE TITLE
Intermittent error {:error, :econnrefused} on SSHKit.run(context, command) with multiple concurrent, longer running commands

### ISSUE THREAD

**Issue by carterbryden** [bitcrowd/sshkit.ex#149]
### Environment

* SSHKit.ex version (`mix deps`):  0.1.0
* Elixir & Erlang/OTP version (`elixir -v`): Elixir 1.9.0-rc.0 (a211223) (compiled with Erlang/OTP 20)
* Operating system (local): ubuntu 16.04
* Operating system (remote): ubuntu 18.04
* SSH version (remote, `ssh -V`): 
local ssh version: OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, OpenSSL 1.0.2g  1 Mar 2016
remote ssh version: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017

### Expected Behavior
I'm expecting that I can run this code below multiple times concurrently:

```
    SSHKit.context(
      address: validaddress
      user: validuser,
      port: validport,
      silently_accept_hosts: true
    )
    |> SSHKit.run(
      "docker run --rm -v $(pwd):/src -v $(pwd)/userapps/user#{app.user_id}/pipeline#{pipeline.id}/app#{
        app.id
      }:/app imagesource/imagename bash -c \"cd app;#{build_env_string(env_map)} asdf local elixir 1.9.0; mix local.rebar --force; mix local.hex --if-missing --force; mix deps.get; mix release --path  ./release --overwrite;\""
    )

```

### Actual Behavior

The code above works most of the time, but intermittently fails if I've previously sent longer running commands (like the docker command above) that are still running.
```
(MatchError) no match of right hand side value: {:error, :econnrefused}
    (sshkit) lib/sshkit.ex:315: anonymous fn/2 in SSHKit.run/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (tapworks) lib/tapworks/docker.ex:25: Tapworks.Docker.build_app_release/3
```

### Other Info

* I've set my max connections on SSHD on the remote to 64000 and restarted
* Tailed the SSHD connection log and saw no obvious issues

**Comment by klappradla** [comment]
Hey @carterbryden, thanx for reporting 💚 

Can you elaborate a bit more on your use case, especially the "concurrently" part? Across how many hosts are you running your commands? We somehow need to reproduce the problem, so the more information you can provide about the setup, the better ✌️ 

Did the problem occur out of a sudden and work with previous versions of `sshkit` or previous server setups?

**Comment by carterbryden** [comment]
Thanks for looking into it!

By concurrently, I mean multiple ssh connections to the same remote host, from the same elixir app using SSHKit, at the same time. It's just across one host but with potentially many connections at the same time. It's greenfield, so I haven't tried older versions of SSHKit and I don't have any reason to believe it's a newly introduced issue.

To reproduce, you could try connecting to the same host multiple times and run some commands that take a little while to finish on each. That often will trigger the error for me, though not always.

Something like this might trigger it:
```
def run_x_times(num \\ 10) do
  for n <- 1..num do
    Task.start(MyApp.ThisModule, :long_running_command, [])
  end
end

def long_running_command() do
  SSHKit.context(
      address: "yourtestaddress"
      port: 22,
      silently_accept_hosts: true
    )
   |> SSHKit.run("longer running command")
end
```

For context, the app is intended to connect to one server with docker (perhaps more later) with SSHKit, spin up docker containers and compile elixir apps on demand for different environments.

**Comment by carterbryden** [comment]
🤦‍♂ 🤦‍♂ 🤦‍♂ 

I was having the same issues with Ansible - turns out it was default rate limiting for SSH incoming connections set on digital ocean droplets. Not an SSHKit.ex issue, Sorry!

**Comment by pmeinhardt** [comment]
Thanks a lot @carterbryden for pointing out what caused the observed behavior ❤️ 
Glad you were able to resolve this 🙌
