### ISSUE TITLE
How to use `silently_accept_hosts` when using SSHKit.SCP ?

### ISSUE THREAD

**Issue by JediLuke** [bitcrowd/sshkit.ex#155]
I've tried passing it as an option to `host/2`, `context/1`, `upload/2`, all with no luck... I see other issues who managed to fix this by passing this option to `connect`, but I'm trying to use `SCP.upload/4` - is there a way to pass this as an option in this case?

**Comment by pmeinhardt** [comment]
Hey @JediLuke, thanks for reaching out 👋

The `:silently_accept_hosts` option, is an option that's related to how a connection is established on `connect`. `SSHKit.SCP.upload/4` in turn expects to receive an open connection.

So if I understand you correctly, I would expect a modified version of the following to work for you, where you add `silently_accept_hosts: true` to the `connect` call on line 20:

https://github.com/bitcrowd/sshkit.ex/blob/871a8d29393e33406f541cf72d94eee9c22b5993/lib/sshkit/scp.ex#L20-L22

In theory, passing that option to one of the higher-level `SSHKit` module functions should work as well, but maybe I am missing something here (or there's a defect somewhere).

Maybe you can provide some more information on which behavior/error you're observing and provide a code snippet so we can try and reproduce it.

Cheers ✌️

**Comment by JediLuke** [comment]
Hi @pmeinhardt 

Thankyou for your help! 

First, apologies for the bad info above, I'm actually just using the highest level `upload/2` function - been reading too much documentation >.<

Here is the code snippet I was trying

```
    droplet_info.ip_addr # this is just an IP as a string, nothing too fancy
    |> SSHKit.host(user: "root")
    |> SSHKit.context()
    |> SSHKit.path("/root/")
    |> SSHKit.upload("./apps/anvil/bash_scripts/anvil_build.sh")
```

This works, so long as I've already added this server to my known_hosts. I'm trying to write a script which will spawn new servers on demand though, and this means I have an annoying manual step of manually SSHing in first. I have changed my script to be like as you suggested

```
{:ok, conn} = SSHKit.SSH.connect(droplet_info.ip_addr, user: "root", silently_accept_hosts: true)
:ok = SSHKit.SCP.upload(conn, anvil_build_script, remote_server_dir, recursive: true)
:ok = SSHKit.SCP.upload(conn, execute_app_script, remote_server_dir, recursive: true)
:ok = SSHKit.SSH.close(conn)
```

And this is now working, so thanks for your help :) you can close this if you feel it's done. Thanks again!

**Comment by pmeinhardt** [comment]
Cool 🙌 In case you want to stick to the higher-level APIs, then I would expect the following to work too:

```elixir
    droplet_info.ip_addr # assuming this is_binary()
    |> SSHKit.host(user: "root", silently_accept_hosts: true)
    |> SSHKit.context()
    |> SSHKit.path("/root/")
    |> SSHKit.upload("./apps/anvil/bash_scripts/anvil_build.sh")
```

Cheers 🙂
