### ISSUE TITLE
Set up continuous integration checks

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/sshkit.ex#16]
We need to add continuous integration checks, e.g. via [Travis-CI](https://travis-ci.com/).

This should run

- [x] unit tests
- [x] functional tests
- [x] styleguide checks ([credo](https://github.com/rrrene/credo))
- [x] documentation checks ([inch_ex](https://github.com/rrrene/inch_ex))

**Comment by tessi** [comment]
Functional tests are being set up in #2

**Comment by tessi** [comment]
Credo checks are being set up in #44

**Comment by tessi** [comment]
More documentation was added in #47 -- there is nothing to check for our CI though

**Comment by tessi** [comment]
we check ALL THE THINGS on travis now
