### ISSUE TITLE
Set up GitHub actions for CI

### ISSUE THREAD

**Issue by pmeinhardt** [bitcrowd/sshkit.ex#165]
Maybe we can toss out our Travis CI configuration and replace it with GitHub actions.

We tried migrating from Travis to Circle before, but couldn't dynamically start Docker containers without hassle.
It looks like [mint](https://github.com/elixir-mint/mint) for instance, also uses Docker with GitHub actions:
https://github.com/elixir-mint/mint/blob/v1.2.0/.github/workflows/main.yml

So maybe that's a way forward. 🧑‍🔬

**Comment by klappradla** [comment]
Wow 🤯! I'd never have had expected this to be so straight forward 👏

**Comment by pmeinhardt** [comment]
> Wow 🤯! I'd never have had expected this to be so straight forward 👏

Me neither. I'm happy it went down so smoothly. 😌
