### ISSUE TITLE
SCP problem

### ISSUE THREAD

**Issue by svoynow** [bitcrowd/sshkit.ex#27]
I think there's an error in the SCP download implementation:
https://github.com/bitcrowd/sshkit.ex/blob/master/lib/sshkit/scp/download.ex

I was having downloads breaking predictably in mid-file, so I dug in to the code a little bit

On lines 35-36
```
        {:data, _, 0, <<1, data :: binary>>} -> warning(options, state, data)
        {:data, _, 0, <<2, data :: binary>>} -> fatal(options, state, data)
```
We're looking for `\x01` or `\x02` sentinel values. 
If I read the "specification" right (https://blogs.oracle.com/janp/entry/how_the_scp_protocol_works)
At this point we're the *sink* not the source, so we shouldn't be listening for those, we should be sending them.

The first byte of the the data element in that tuple is just normal data. So if we encounter a `\x02` byte anywhere in the file being downloaded it bails out.

You can see this w/ the minimal reproduction case, using a file w/ just the one byte.
Create a file like so `echo -e "\x02" > boom`, and then try to download it.

**Comment by pmeinhardt** [comment]
Thanks a lot for reporting *and* also fixing this! Top priority for me now is to definitely get the functional tests onto master and add cases for the basic SSH and SCP modules so we prevent this kind of issue.
