### ISSUE TITLE
Rename `SSHKit.pwd` to `SSHKit.path`?

### ISSUE THREAD

**Issue by brienw** [bitcrowd/sshkit.ex#33]
As I was adding the SCP context operations, I started having thoughts about the naming of `SSHKit.pwd`. `pwd` is the "print working directory" command which seems like an odd name here. Perhaps something like `SSHKit.dir`, `SSHKit.path`, `SSHKit.cd` or `SSHKit.chdir` would be more intuitive. I'm personally partial to `SSHKit.path` since it seems most understandable in the context of a context.

**Comment by tessi** [comment]
Thanks @brienw for the suggestion. We agree and choose to follow your suggestion to rename it to `SSHKit.path`.

This will be part of verision `0.0.2`.

**Comment by brienw** [comment]
Thanks, guys!
