### ISSUE TITLE
Release 0.0.2

### ISSUE THREAD

**Issue by tessi** [bitcrowd/sshkit.ex#42]
* Figure out which PRs we plan to merge (or issues to fix) until we release
  * [x] #35
  * [x] #36 
  * [x] #37 
  * [x] #46
* [x] Update Changelog
* [x] Release and tag
* [x] Upload package to hex.pm

**Comment by pmeinhardt** [comment]
The issues listed here are fixed #35, #36, #37, #46 as of f09510f25af0c9e1a12b31a9808f2163520c452d.
More improvements to come, but this may be a good point, to create another release.

😜

**Comment by tessi** [comment]
https://hex.pm/packages/sshkit it's there 🎉
