### ISSUE TITLE
Allow SSH.connect to receive a lambda where the connection is only open within the lambda

### ISSUE THREAD

**Issue by tessi** [bitcrowd/sshkit.ex#72]
We should allow optionally passing lambdas to `SSH.connect`, which opens the connection only within the passed lambda:

```
SSH.connect host.ip, Keyword.merge(@defaults, options), fn(conn) ->
  SCP.upload(conn, local, remote)
end

```

Any thoughts?

**Comment by pmeinhardt** [comment]
Just to clarify: You mean, so it is auto-closed after running the function/lambda?

**Comment by pmeinhardt** [comment]
Sounds reasonable to me. I'm wondering why this doesn't seem to be a common pattern with Elixir. Deffo something I've seen in Python, Ruby, JavaScript…, but for Elixir?

E.g. [`Elixir.File`](https://hexdocs.pm/elixir/File.html) from the standard library you have to [`open/2,3`](https://hexdocs.pm/elixir/File.html#open/2) and explicitly [`close/1`](https://hexdocs.pm/elixir/File.html#close/1).

I think it would be very convenient. 👍

**Comment by tessi** [comment]
> Just to clarify: You mean, so it is auto-closed after running the function/lambda?

yep, that's what i thought

**Comment by tessi** [comment]
cons against this feature is that we have a method `SSH.connect` which behaves differently depending on their arguments. We *guess* that is why the standard library doesn't implement this behaviour.

maybe we should provide this functionality in a different method, or not at all (and just document that one should not forget to manually close the connection)

**Comment by tessi** [comment]
There is [`File.open/3`](https://hexdocs.pm/elixir/File.html#open/3) which does exactly that (opening the file only for the given function). -- so it seems to be a common pattern in elixir :)

**Comment by pmeinhardt** [comment]
:man_facepalming:
