### ISSUE TITLE
Find out why setting the atime during scp uploads has a time difference in tests

### ISSUE THREAD

**Issue by tessi** [bitcrowd/sshkit.ex#78]
While implementing functional tests for SCP operations we discovered that setting the atime of remote files produces a different atime-timestamp than the uploaded file.

We temporarily removed the atime check in [this commit](https://github.com/bitcrowd/sshkit.ex/pull/59/commits/5f321188fc3c4a536966b3fc47238b0382e52751).

See if we can re-introduce atime-tests and maybe fix the underlying issue.

**Comment by pmeinhardt** [comment]
@tessi, @brienw, looking at the [tests on `master`](https://github.com/bitcrowd/sshkit.ex/blob/master/test/sshkit/scp_functional_test.exs#L99) I think this can be closed, right?

Feel free to re-open if not 👋
