### ISSUE TITLE
Define module boundaries and public vs. internal API

### ISSUE THREAD

**Issue by klappradla** [bitcrowd/sshkit.ex#90]
Moving over a discussion started in #82 : where do we want to draw module boundaries that allow sensible testing and where do we want to draw the line between public and internal API?

Thanx to @pmeinhardt we have some artworks available:

### Module Boundaries

current organization:
```
+--------------------+
| SSHKit             |
+--------------------+
|       | SSHKit.SCP |
|       +------------+
| SSHKit.SSH         |
+--------------------+
```

Possible different organization: dissecting one level further to better isolate the Erlang modules

```
+--------------------------------------------+
| SSHKit.SSH                                 |
+-----------------------+--------------------+
| SSHKit.SSH.Connection | SSHKit.SSH.Channel |
+-----------------------+--------------------+
| :ssh                  | :ssh_connection    |
+-----------------------+--------------------+
```

### Public vs. Internal API

Citing @pmeinhardt 
> a secondary contribution of SSHKit are the `SSHKit.SSH` and the `SSHKit.SCP` modules

> Everything inside of/below these, I would consider internal/private — in particular the modules `SSHKit.SSH.{Connection, Channel}` and `SSHKit.SCP.{Command, Download, Upload}`

**Comment by pmeinhardt** [comment]
@klappradla, is this issue still "a thing" or is it okay to close it? Do we need to document anything?

**Comment by klappradla** [comment]
Well, for me personally it's as much "a thing" as I'd love to have a discussion and respective coding sessions on it ✌️ But it's obviously neither a bug nor a feature or a blocker in any sense and I thanx to JS adventures also don't see myself diving into this tomorrow...

So I guess it's fine to be closed. But it would probably be of use to move the diagrams somewhere. I could imagine something like a `ROADMAP.MD` or `VISION.MD` if that's a maintainable pattern 🤔 
What you think?

If there's just no use for this, feel of course also free to just close it without further action ✌️

**Comment by pmeinhardt** [comment]
We could even move the first of the diagrams to the README section on SSHKit modules to provide a better, more graphic overview: https://github.com/bitcrowd/sshkit.ex#modules

What do you think?

**Comment by klappradla** [comment]
Sure 👍
